spring:
  data:
    mongodb:
      uri: mongodb+srv://springuser:journal_123@cluster0.ite0erw.mongodb.net/?journaldb=Cluster0
      database: journaldb
      auto-index-creation: true

  redis:
    uri: redis://default:wl6fJ8lNC3EXhzxCLymRbZGYBqOxMPP3@redis-16324.c212.ap-south-1-1.ec2.cloud.redislabs.com:16324


server:
    port: 8080
    servlet:
      context-path: /journal

